# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e477cba23eadaf05eafefc17033bfa62f05192f768e5d6a102c685f1e9110b959aaa02b56fb78b47a283ff7667db9b9bbbc41a56976e7dd076e617d93af7e73d

test:
  secret_key_base: cb4c1d15811631bf7be926bce41e01156a27812ce74c8617832e876cf49ef5c6d620647a4c5bcea8b910677e8c84570ea415d558dcb70b04e92b76e7fa860c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
